language: rust
rust:
    - stable
    - beta
    - nightly

env:
- 
- CARGO_BUILD_TARGET=arm-linux-androideabi
- CARGO_BUILD_TARGET=x86_64-linux-android
- CARGO_BUILD_TARGET=aarch64-linux-android

script:
  - if [[ $CARGO_BUILD_TARGET ]]; then
      rustup target add $CARGO_BUILD_TARGET;
    fi
  - cargo build

notifications:
    email: false
