dist: trusty
language: rust
services: docker
sudo: required

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.

env:
  global:
    - CRATE_NAME=rust-mdns-responder

rust:
    - stable
    - beta
    - nightly

env:
- TARGET=x86_64-unknown-linux-gnu DISABLE_TESTS=1
- TARGET=arm-linux-androideabi DISABLE_TESTS=1
- TARGET=x86_64-linux-android DISABLE_TESTS=1
- TARGET=aarch64-linux-android DISABLE_TESTS=1

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh
notifications:
    email: false
