language: rust
rust:
    - stable
    - beta
    - nightly

env:
- TARGET=x86_64-unknown-linux-gnu
- TARGET=arm-linux-androideabi
- TARGET=x86_64-linux-android
- TARGET=aarch64-linux-android

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh
notifications:
    email: false
